version: 2

jobs:
  build:
    docker:
      - image: peterjclaw/sr-dev-ldap
        command: ['--loglevel', 'debug', '--cmd', 'sed s_ldap://localhost__ -i /container/service/slapd/startup.sh']
        environment:
          LDAP_LOG_LEVEL: 4

    steps:
      - checkout
