version: 2

jobs:
  build:
    docker:
      - image: circleci/python:2.7
      - image: peterjclaw/sr-dev-ldap

    steps:
      - checkout

      - run: git submodule update --init

      # Set up a cached virtualenv in which to install dependencies
      - restore_cache:
          name: Restore dependency cache
          key: deps-venv-{{ .Branch }}-{{ checksum ".circleci/requirements.txt" }}
      - run:
          name: Install base dependencies
          command: sudo apt install libsasl2-dev python-dev libldap2-dev libssl-dev ldap-utils
      - run:
          name: Create virtualenv
          command: |
            python -m virtualenv venv
            . venv/bin/activate
            pip install -r .circleci/requirements.txt
      - save_cache:
          name: Save dependency cache
          key: deps-venv-{{ .Branch }}-{{ checksum ".circleci/requirements.txt" }}
          paths:
            - "venv"

      - run:
          name: Configure LDAP connection
          command: |
            echo "[ldap]" > libnemesis/srusers/local.ini
            echo "password = 123456" >> libnemesis/srusers/local.ini

      - run:
          name: Wait for LDAP server to be running
          command: sleep 5

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            ./run-tests
