version: 2

jobs:
  build:
    docker:
      - image: circleci/python:2.7

      - image: peterjclaw/sr-dev-ldap
        command: ['--copy-service', '--loglevel', 'debug']

    steps:
      - checkout

      - run: git submodule update --init

      # Set up a cached virtualenv in which to install dependencies
      - restore_cache:
          name: Restore dependency cache
          key: deps-venv-{{ .Branch }}-{{ checksum ".circleci/requirements.txt" }}
      - run:
          name: Install base dependencies
          command: sudo apt install libsasl2-dev python-dev libldap2-dev libssl-dev ldap-utils
      - run:
          name: Create virtualenv
          command: |
            python -m virtualenv venv
            . venv/bin/activate
            pip install -r .circleci/requirements.txt
      - save_cache:
          name: Save dependency cache
          key: deps-venv-{{ .Branch }}-{{ checksum ".circleci/requirements.txt" }}
          paths:
            - "venv"

      - run:
          name: Configure LDAP connection
          command: |
            echo "[ldap]" > libnemesis/srusers/local.ini
            echo "host = localhost:3890" >> libnemesis/srusers/local.ini
            echo "password = 123456" >> libnemesis/srusers/local.ini

      - run:
          name: Wait for LDAP server to be running
          command: |
            set +e
            for x in $(seq 60)
            do
              ldapsearch -h localhost -p 3890 -D 'cn=Manager,o=sr' -w 123456 -b 'o=sr'
              if [ $? -ne 0 ]
              then
                sleep 0.5
              else
                exit
              fi
            done

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            ./run-tests
