version: 2

jobs:
  build:
    docker:
      - image: peterjclaw/sr-dev-ldap
        command: ['--dont-touch-etc-hosts', '--loglevel', 'debug']
        environment:
          LDAP_LOG_LEVEL: 4
          HOSTNAME: localhost

    steps:
      - checkout
